# Copyright 2020 NXP Semiconductors
# This page was inspired on MediaPipe page: https://github.com/google/mediapipe
# SPDX-License-Identifier: BSD-3-Clause

remote_theme: pmarsceill/just-the-docs

logo: PyeIQ

search_enabled: true
search_tokenizer_separator: /[\s/]+/

heading_anchors: true

aux_links:
  "Source Code Available on CAF":
    - "https://source.codeaurora.org/external/imxsupport/pyeiq/"

footer_content: "&copy; 2020 NXP Semiconductors | <a href=\"https://source.codeaurora.org/external/imxsupport/pyeiq/tree/LICENSE.md\">LICENSE TERMS</a> | <a href=\"https://www.nxp.com/eiq\">eIQ&trade; NXP Semiconductors</a>"

color_scheme: nil

#ga_tracking: UA-140696581-2
